### ISSUE TITLE
train_batch_size represents what?

### ISSUE THREAD

**Issue by nick89216kuo** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#17]
Hello researcher!
I've been studying the ProtoNet example you provided recently, and I changed the dataset to ESC-50. However, I encountered some issues in the process. When I change the train_batch_size parameter to any number greater than 1, the program fails to run. Unlike in the MAML example, I haven't encountered this problem. I would like to ask about the meaning of the train_batch_size parameter and whether it's a mistake in my configuration. Below are my configuration files and the execution report.

config
base:                                                              
  n_way: 5                                                     
  k_shot: 1
  q_queries: 1                                                          
  distance: 'l2'                                                                
  task_type: 'PROTO_VAR_Kaggle_5_second_'
  cuda: 0
  num_repeats: 1
  out_dim: 128

models: ['Hybrid']

hyper:
  initial_lr: 0.0005 #0.01 #0.005
  # The lowest lr that is ever hit                                                             
  min_lr: 0.0001
  # Patience for val loss
  patience: 100000
  # Factor of lr reduction-new_lr = lr*factor
  factor: 0.1                 
  # Number of episodes to warm up for before using scheduler
  scheduler_warm_up: 20                                                                    

training:
  epochs: 1000 #1500
  episodes_per_epoch: 10
  train_batch_size: 5 # 10/20/50 

  # How many tasks we want at each step
  val_tasks: 200
  test_tasks: 10000
  break_threshold: 1000

  # Episodes between validation steps
  eval_spacing: 100   
  
  trans_batch: False

  # Number workers for the dataloaders
  num_workers: 4                                                               

data:
  variable: False
  name: 'ESC' # Kaggle_18
  norm: 'global'
  type: 'spec' # rawtospec/spec/variable_spec
  fixed: True

  fixed_path: 'dataset_/splits/ESC_paper_splits.npy'
  data_path: '/home/mitlab/kuo/ESC-50-master/ESC_spec'

# Split percentages for train/val/test
split:
  train: 0.7
  val: 0.1
  test: 0.2

Traceback (most recent call last):
  File "BaseLooperProto.py", line 106, in <module>
    pre, post, loss, post_std = single_run_main(params=params, 
  File "/home/mitlab/kuo/Proto_Kaggle18/ProtoMain.py", line 155, in single_run_main
    pre, post, loss, post_std = fit(
  File "/home/mitlab/kuo/Proto_Kaggle18/fit_proto.py", line 103, in fit
    val_loss, val_pre, val_post, val_post_std = validation_step(valLoader, learner,
  File "/home/mitlab/kuo/Proto_Kaggle18/fit_proto.py", line 208, in validation_step_fixed
    x, y = prep_batch(batch, params['training']['train_batch_size'])
  File "/home/mitlab/kuo/Proto_Kaggle18/all_prep_batches.py", line 41, in prep_batch_fixed
    x = x.reshape(meta_batch_size, (n_way*k_shot + n_way*q_queries),
RuntimeError: shape '[5, 10, 128, 157]' is invalid for input of size 200960

**Comment by CHeggan** [comment]
Hi there, thank you for reaching out. 

So train_batch_size is the number of few-shot tasks that belong to a single batch. This is different from episodes per epoch which controls how many batches of tasks are considered in a single epoch. 

Looking into the actual code, train_batch_size is the same as meta_batch_size, which if you want to confirm can be found in the prep_batch_fns.py file:
```
x = x.reshape(meta_batch_size, (n_way*k_shot + n_way*q_queries), x.shape[-2], x.shape[-1])
```

The Proto Kaggle code, as it was setup and released as an example for variable length sequences, has a few legacy or variable specific parts in it. 

Now for the part that is causing your problem:
 - For variable length setting we use a validation batch size of 1 not train_batch_size. This was implemented so that gpu memory wouldn't overflow if a large eval clip was sampled
 - As you moved the code to fixed length setting, it is now using fixed length validation step, which does not have this requirement and used batches of size train_batch_size
 - The code I released was quickly setup for a test example and so I missed adding in the switch for this in task loader setup

I think the actual fix is straight forward, the val and eval taskloaders located in ProtoMain.py just need their num_task argument changed from 
```
num_tasks = 1
```
to 
```
val_batch_size = 1 if params['data']['variable'], else params['training']['train_batch_size']
num_tasks = val_batch_size
```
Unfortunately I am not able to verify this fixes the issue at the moment, but hopefully it works!

I have updated the repo so you should just be able to grab that.

Best,
Calum
